### PR TITLE
Get user info from API on payment page

### LINKED ISSUE #538: Authentication issue on redirect to payment page after cybersource payment
A similar issue cropped up with #416 & #426 but was fixed, it is now broken again.  Django seems to think the user is not authenticated when returning from cybersource.

### PR DESCRIPTION
**Pull request by mbertrand**
#### What are the relevant tickets?
Fixes #538

#### What's this PR do?
- Removes `user` from js SETTINGS
- Use `state.entities.currentUser` on the `PaymentPage` instead

#### How should this be manually tested?
- Make a payment on the payment page, nothing should break.

### CODE REVIEW

File: static/js/components/Payment.js [hunk 1]
```diff
@@ -28,7 +29,8 @@ export default class Payment extends React.Component<*, void> {
     sendPayment: () => void,
     setPaymentAmount: (event: InputEvent) => void,
     setSelectedBootcampRunKey: (event: InputEvent) => void,
-    showDialog: (dialogKey: string) => void
+    showDialog: (dialogKey: string) => void,
+    currentUser: () => Promise<HttpAuthResponse<User>>
```
Comment (noisecapella) [inline static/js/components/Payment.js:33]: I think this should just be `?CurrentUser` since it's there's no `Promise` being resolved and the code below is using the object directly and not via `.body`

File: static/js/pages/PaymentPage.js [hunk 2]
```diff
@@ -47,7 +49,8 @@ type Props = {
   setSelectedBootcampRunKey: (runKey: number) => void,
   setTimeoutActive: (active: boolean) => void,
   setToastMessage: (payload: any) => void,
-  showDialog: (dialogKey: string) => void
+  showDialog: (dialogKey: string) => void,
+  currentUser: () => Promise<HttpAuthResponse<User>>
```
Comment (noisecapella) [inline static/js/pages/PaymentPage.js:53]: Should this be `?CurrentUser`?

Comment (mbertrand) [reply static/js/pages/PaymentPage.js]: Thanks, changes made.
